FROM node:lts-alpine3.22

RUN mkdir -p /app/auditoria /app/common_library && chown -R node:node /app
WORKDIR /app/auditoria

COPY --chown=node:node common_library/activos-config ../common_library/activos-config
COPY --chown=node:node auditoria/package*.json ./

ARG NEXUS_URL
RUN if [ -z "${NEXUS_URL}" ]; then \
      echo "ERROR: El build-arg NEXUS_URL es obligatorio" >&2; \
      exit 1; \
    fi && \
    echo "@activos:registry=${NEXUS_URL}" >> .npmrc

USER node
RUN cd ../common_library/activos-config && npm ci && npm run build
RUN npm install

COPY --chown=node:node auditoria/ .

# Express con nodemon para hot-reload
CMD ["npx", "nodemon", "--watch", "src", "src/index.js"]
