services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: activos_nexus
    restart: unless-stopped
    ports:
      - "20002:8081"
    volumes:
      - nexus_data:/nexus-data
    environment:
      INSTALL4J_ADD_VM_PARAMS: >-
        -Xms512m -Xmx1024m
        -XX:MaxDirectMemorySize=512m

volumes:
  nexus_data:
