services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: dockerfile

    container_name: jenkins
    restart: unless-stopped
    group_add:
      - "${DOCKER_HOST_GID}"
    ports:
      - "8083:8080"
      - "50003:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

  app-db:
    image: postgres:16-alpine
    container_name: activos_db
    env_file:
      - ./.env

    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT

    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      PGPORT: $POSTGRES_PORT

    volumes:
      - postgres_data:/var/lib/postgres/data
  backend:
    container_name: activos_backend
    image: ${DOCKER_REGISTRY:-local_activos}/backend:${TAG:-latest}
    build:
      dockerfile: dockerfile
      context: ./backend
    user: ${UID:-1000}:${GID:-1000}
    env_file:
      - ./.env

    ports:
      - 3000:3000

    depends_on:
      app-db:
        condition: service_started

    command: "npm run start:dev"

  frontend:
    container_name: activos_frontend
    image: ${DOCKER_REGISTRY:-local_activos}/frontend:${TAG:-latest}
    build:
      dockerfile: dockerfile2
      context: ./frontend

    user: ${UID:-1000}:${GID:-1000}
    env_file:
      - ./.env

    ports:
      - 80:8084

    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data:
  jenkins_home:
