FROM node:lts-alpine3.22

RUN mkdir -p /app && chown -R node:node /app
WORKDIR /app

COPY --chown=node:node package*.json ./

ARG NEXUS_URL
RUN if [ -z "${NEXUS_URL}" ]; then \
      echo "ERROR: El build-arg NEXUS_URL es obligatorio" >&2; \
      exit 1; \
    fi && \
    echo "@activos:registry=${NEXUS_URL}" >> .npmrc

USER node
RUN npm install

COPY --chown=node:node . .

CMD ["npm", "run", "start:dev"]
