// DO NOT EDIT — auto-generated by flutter create.
// Allows Flutter to pick the correct entry-point file depending on the Dart
// define passed via --dart-define.
#include "Flutter/Generated.xcconfig"
#include "Flutter/Flutter.xcconfig"
